# Generated by Django 4.1.5 on 2023-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('matched', 'matched'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='ratio_risk',
            field=models.FloatField(default=0.03),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax',
            field=models.FloatField(default=0.001),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_fee',
            field=models.FloatField(default=0.0015),
        ),
    ]
