# Generated by Django 4.1.5 on 2023-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_transaction_status_alter_account_ratio_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('low_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('match_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cut_loss_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.CharField(blank=True, choices=[('KDH', 'KDH'), ('HPG', 'HPG'), ('EIB', 'EIB'), ('FPT', 'FPT')], max_length=6, null=True),
        ),
    ]
