# Generated by Django 4.1.5 on 2023-04-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stockprice_alter_transaction_cut_loss_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
