# Generated by Django 4.1.5 on 2023-04-16 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_datenottrading'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
